nodes = \
{'Acton Central': (('3',), (438.5, 643.0)),
 'Acton Town': (('3',), (327.5, 554.0)),
 'Aldgate': (('1',), (1387.0, 671.0)),
 'Aldgate East': (('1',), (1440.5, 678.0)),
 'All Saints': (('2',), (1590.0, 662.0)),
 'Alperton': (('4',), (318.5, 931.0)),
 'Amersham': (('10',), (28.5, 1311.0)),
 'Anerley': (('4',), (1377.0, 89.0)),
 'Angel': (('1',), (1203.5, 841.0)),
 'Archway': (('2', '3'), (1135.5, 1109.0)),
 'Arnos Grove': (('4',), (1377.0, 1230.0)),
 'Arsenal': (('2',), (1308.5, 1029.0)),
 'Baker Street': (('1',), (866.0, 804.0)),
 'Balham': (('3',), (893.0, 154.0)),
 'Bank': (('1',), (1233.0, 668.0)),
 'Barbican': (('1',), (1218.5, 765.0)),
 'Barking': (('4',), (1820.5, 857.0)),
 'Barkingside': (('5',), (1838.5, 1112.0)),
 'Barons Court': (('2',), (600.0, 535.0)),
 'Bayswater': (('1',), (705.0, 761.0)),
 'Beckton': (('3',), (1975.5, 464.0)),
 'Beckton Park': (('3',), (1898.0, 541.0)),
 'Becontree': (('5',), (1875.5, 907.0)),
 'Belsize Park': (('2',), (1017.0, 1014.0)),
 'Bermondsey': (('2',), (1360.5, 529.0)),
 'Bethnal Green': (('2',), (1501.0, 786.0)),
 'Blackfriars': (('1',), (1166.5, 566.0)),
 'Blackhorse Road': (('3',), (1538.0, 1082.0)),
 'Blackwall': (('2',), (1639.5, 627.0)),
 'Bond Street': (('1',), (869.0, 705.0)),
 'Borough': (('1',), (1138.5, 398.0)),
 'Boston Manor': (('4',), (247.5, 496.0)),
 'Bounds Green': (('3', '4'), (1377.0, 1202.0)),
 'Bow Church': (('2',), (1588.5, 741.0)),
 'Bow Road': (('2',), (1613.5, 765.0)),
 'Brent Cross': (('3',), (913.5, 1118.0)),
 'Brixton': (('2',), (1030.5, 209.0)),
 'Brockley': (('2',), (1375.5, 264.0)),
 'Bromley-by-Bow': (('2', '3'), (1678.5, 759.0)),
 'Brondesbury': (('2',), (712.5, 962.0)),
 'Brondesbury Park': (('2',), (680.0, 965.0)),
 'Buckhurst Hill': (('5',), (1712.5, 1257.0)),
 'Burnt Oak': (('4',), (836.5, 1197.0)),
 'Bushey': (('8',), (566.0, 1297.0)),
 'Caledonian Road': (('2',), (1255.5, 974.0)),
 'Caledonian Road & Barnsbury': (('2',), (1283.5, 944.0)),
 'Camden Road': (('2',), (1165.0, 970.0)),
 'Camden Town': (('2',), (1070.5, 947.0)),
 'Canada Water': (('2',), (1461.0, 529.0)),
 'Canary Wharf': (('2', '3'), (1590.0, 527.0)),
 'Canning Town': (('3',), (1708.0, 629.0)),
 'Cannon Street': (('1',), (1215.5, 606.0)),
 'Canonbury': (('2',), (1434.5, 949.0)),
 'Canons Park': (('5',), (648.5, 1175.0)),
 'Carpenders Park': (('7',), (567.5, 1267.0)),
 'Chaifont & Latimer': (('9',), (159.0, 1311.0)),
 'Chalk Farm': (('2',), (1044.0, 986.0)),
 'Chancery Lane': (('1',), (1144.5, 706.0)),
 'Charing Cross': (('1',), (1030.5, 585.0)),
 'Chesham': (('10',), (77.5, 1338.0)),
 'Chigwell': (('5',), (1776.5, 1199.0)),
 'Chiswick Park': (('3',), (357.0, 536.0)),
 'Chorleywood': (('8',), (240.5, 1294.0)),
 'Clapham Common': (('2',), (941.5, 207.0)),
 'Clapham High Street': (('2,'), (968.9, 240.2)),
 'Clapham Junction': (('2',), (811.5, 292.0)),
 'Clapham North': (('2',), (970.0, 231.0)),
 'Clapham South': (('2', '3'), (919.5, 181.0)),
 'Cockfosters': (('5',), (1377.0, 1313.0)),
 'Colindale': (('4',), (862.0, 1169.0)),
 'Colliers Wood': (('3',), (819.0, 82.0)),
 'Covent Garden': (('1',), (1058.5, 675.0)),
 'Crossharbour': (('2',), (1588.5, 448.0)),
 'Crouch Hill': (('3',), (1273.0, 1116.0)),
 'Croxley': (('7',), (278.5, 1286.0)),
 'Crystal Palace': (('3', '4'), (1325.0, 73.0)),
 'Custom House for ExCeL': (('3',), (1824.5, 615.0)),
 'Cutty Sark for Maritime Greenwich': (('2',), (1588.5, 346.0)),
 'Cyprus': (('3',), (1923.5, 517.0)),
 'Dagenham East': (('5',), (1924.5, 961.0)),
 'Dagenham Heathway': (('5',), (1908.0, 941.0)),
 'Dalston Junction': (('2',), (1461.0, 906.0)),
 'Dalston Kingsland': (('2',), (1473.0, 921.0)),
 'Debden': (('6',), (1707.0, 1311.0)),
 'Denmark Hill': (('2',), (1173.24, 222.202)),
 'Deptford Bridge': (('2',), (1588.5, 289.0)),
 'Devons Road': (('2',), (1588.5, 717.0)),
 'Dollis Hill': (('3',), (703.5, 1036.0)),
 'Ealing Broadway': (('3',), (281.5, 703.0)),
 'Ealing Common': (('3',), (315.5, 628.0)),
 "Earl's Court": (('1', '2'), (677.0, 535.0)),
 'East Acton': (('2',), (495.0, 706.0)),
 'East Finchley': (('3',), (1135.5, 1169.0)),
 'East Ham': (('3', '4'), (1795.5, 833.0)),
 'East India': (('2', '3'), (1678.0, 627.0)),
 'East Putney': (('2', '3'), (660.5, 327.0)),
 'Eastcote': (('5',), (290.5, 1146.0)),
 'Edgware': (('5',), (799.5, 1233.0)),
 'Edgware Road': (('1',), (739.0, 848.0)),
 'Elephant & Castle': (('1', '2'), (1072.0, 335.0)),
 'Elm Park': (('6',), (1954.0, 986.0)),
 'Elverson Road': (('2',), (1588.5, 264.0)),
 'Embankment': (('1',), (1048.0, 521.0)),
 'Epping': (('6',), (1709.5, 1357.0)),
 'Euston': (('1',), (1081.0, 854.0)),
 'Euston Square': (('1',), (1070.5, 823.0)),
 'Fairlop': (('5',), (1840.0, 1138.0)),
 'Farringdon': (('1',), (1190.5, 795.0)),
 'Finchley Central': (('4',), (1135.5, 1195.0)),
 'Finchley Road': (('2',), (798.0, 939.0)),
 'Finchley Road & Frognal': (('2',), (933.0, 1010.0)),
 'Finsbury Park': (('2',), (1350.0, 1070.0)),
 'Forest Hill': (('3',), (1375.5, 176.0)),
 'Fulham Broadway': (('2',), (660.5, 421.0)),
 'Gallions Reach': (('3',), (1949.0, 491.0)),
 'Gants Hill': (('4',), (1810.5, 1048.0)),
 'Gloucester Road': (('1',), (737.5, 545.0)),
 'Golders Green': (('3',), (934.5, 1095.0)),
 'Goldhawk Road': (('2',), (558.5, 594.0)),
 'Goodge Street': (('1',), (1032.0, 733.0)),
 'Gospel Oak': (('2',), (1073.5, 1042.0)),
 'Grange Hill': (('5',), (1806.0, 1202.0)),
 'Great Portland Street': (('1',), (962.5, 829.0)),
 'Green Park': (('1',), (884.0, 638.0)),
 'Greenford': (('4',), (210.5, 916.0)),
 'Greenwich': (('2',), (1590.0, 316.0)),
 'Gunnesbury': (('3',), (385.5, 455.0)),
 'Hackney Central': (('2',), (1502.5, 893.0)),
 'Hackney Wick': (('2',), (1603.0, 879.0)),
 'Haggerston': (('2',), (1462.5, 865.0)),
 'Hainault': (('5',), (1840.0, 1166.0)),
 'Hammersmith': (('2',), (563.0, 535.0)),
 'Hampstead': (('2', '3'), (962.5, 1069.0)),
 'Hamstead Heath': (('2',), (1023.0, 1044.0)),
 'Hanger Lane': (('3',), (302.5, 823.0)),
 'Harlesden': (('3',), (560.0, 996.0)),
 'Harringay Green Lanes': (('3',), (1434.5, 1129.0)),
 'Harrow & Wealdstone': (('5',), (563.0, 1180.0)),
 'Harrow-on-the-Hill': (('5',), (453.5, 1104.0)),
 'Hatch End': (('6',), (567.5, 1240.0)),
 'Hatton Cross': (('5', '6'), (132.0, 379.0)),
 'Headstone Lane': (('5',), (567.5, 1212.0)),
 'Heathrow Terminals 1,2,3': (('6',), (98.0, 345.0)),
 'Hendon Central': (('3', '4'), (885.5, 1146.0)),
 'Heron Quays': (('2',), (1588.5, 503.0)),
 'High Barnet': (('5',), (1134.0, 1320.0)),
 'High Street Kensington': (('1',), (706.5, 648.0)),
 'Highbury & Islington': (('2',), (1326.5, 946.0)),
 'Highgate': (('3',), (1135.5, 1141.0)),
 'Hillingdon': (('6',), (110.0, 1180.0)),
 'Holborn': (('1',), (1084.0, 706.0)),
 'Holland Park': (('2',), (654.5, 705.0)),
 'Holloway Road': (('2',), (1285.0, 1005.0)),
 'Homerton': (('2',), (1541.0, 878.0)),
 'Honor Oak Park': (('3',), (1375.5, 202.0)),
 'Hornchurch': (('6',), (1968.5, 1002.0)),
 'Hounslow Central': (('4',), (178.0, 422.0)),
 'Hounslow East': (('4',), (199.0, 449.0)),
 'Hounslow West': (('5',), (157.5, 403.0)),
 'Hoxton': (('1', '2'), (1462.5, 823.0)),
 'Hyde Park Corner': (('1',), (847.0, 613.0)),
 'Ickenham': (('6',), (156.0, 1178.0)),
 'Imperial Wharf': (('2',), (712.5, 392.0)),
 'Island Gardens': (('2',), (1588.5, 391.0)),
 'Kennington': (('2',), (1029.0, 286.0)),
 'Kensal Green': (('2', '3'), (563.0, 940.0)),
 'Kensal Rise': (('2',), (620.5, 964.0)),
 'Kensington (Olympia)': (('2',), (662.0, 610.0)),
 'Kentish Town': (('2',), (1134.0, 1042.0)),
 'Kentish Town West': (('2',), (1107.5, 1026.0)),
 'Kenton': (('4',), (563.0, 1153.0)),
 'Kew Gardens': (('3', '4'), (385.5, 415.0)),
 'Kilburn': (('2',), (751.0, 986.0)),
 'Kilburn High Road': (('2',), (681.5, 896.0)),
 'Kilburn Park': (('2',), (569.0, 887.0)),
 'King George V': (('3',), (1935.5, 455.0)),
 "King's Cross St. Pancras": (('1',), (1146.0, 823.0)),
 'Kingsbury': (('4',), (647.0, 1121.0)),
 'Knightsbridge': (('1',), (822.0, 591.0)),
 'Ladbroke Grove': (('2',), (591.0, 782.0)),
 'Lambeth North': (('1',), (1051.0, 385.0)),
 'Lancaster Gate': (('1',), (793.5, 706.0)),
 'Langdon Park': (('2',), (1588.5, 690.0)),
 'Latimer Road': (('2',), (570.5, 762.0)),
 'Leicester Square': (('1',), (1030.5, 654.0)),
 'Lewisham': (('2',), (1588.5, 236.0)),
 'Leyton': (('3',), (1709.5, 930.0)),
 'Leyton Midland Road': (('3',), (1644.5, 946.0)),
 'Leytonstone': (('3', '4'), (1711.0, 999.0)),
 'Leytonstone High Road': (('3',), (1752.5, 947.0)),
 'Limehouse': (('2',), (1524.0, 629.0)),
 'Liverpool Street': (('1',), (1338.5, 749.0)),
 'London Bridge': (('1',), (1251.0, 529.0)),
 'London City Airport': (('3',), (1890.5, 497.0)),
 'Loughton': (('6',), (1709.5, 1288.0)),
 'Maida Vale': (('2',), (585.0, 872.0)),
 'Manor House': (('2', '3'), (1375.5, 1107.0)),
 'Mansion House': (('1',), (1190.5, 588.0)),
 'Marble Arch': (('1',), (826.5, 705.0)),
 'Marylebone': (('1',), (799.5, 847.0)),
 'Mile End': (('2',), (1556.0, 785.0)),
 'Mill Hill East': (('4',), (1097.0, 1248.0)),
 'Monument': (('1',), (1274.5, 623.0)),
 'Moor Park': (('6', '7'), (286.0, 1252.0)),
 'Moorgate': (('1',), (1254.0, 748.0)),
 'Morden': (('4',), (764.0, 27.0)),
 'Mornington Crescent': (('2',), (1055.5, 907.0)),
 'Mudchute': (('2',), (1590.0, 421.0)),
 'Neasden': (('3',), (677.0, 1060.0)),
 'New Cross': (('2',), (1461.0, 318.0)),
 'New Cross Gate': (('2',), (1375.5, 320.0)),
 'Newbury Park': (('4',), (1840.0, 1084.0)),
 'North Acton': (('2', '3'), (469.5, 703.0)),
 'North Ealing': (('3',), (317.0, 739.0)),
 'North Greenwich': (('3',), (1659.5, 537.0)),
 'North Harrow': (('5',), (394.0, 1144.0)),
 'North Wembley': (('4',), (563.0, 1066.0)),
 'Northfields': (('3',), (273.0, 520.0)),
 'Northolt': (('5',), (196.0, 996.0)),
 'Northwick Park': (('4',), (527.5, 1107.0)),
 'Northwood': (('6',), (310.0, 1227.0)),
 'Northwood Hills': (('6',), (336.5, 1202.0)),
 'Norwood Junction': (('4',), (1375.5, 60.0)),
 'Notting Hill Gate': (('1', '2'), (699.0, 705.0)),
 'Oakwood': (('5',), (1377.0, 1283.0)),
 'Old Street': (('1',), (1252.5, 808.0)),
 'Osterley': (('4',), (222.5, 472.0)),
 'Oval': (('2',), (1010.0, 274.0)),
 'Oxford Circus': (('1',), (933.0, 705.0)),
 'Paddington': (('1',), (666.5, 845.0)),
 'Park Royal': (('3',), (317.0, 776.0)),
 'Parsons Green': (('2',), (660.5, 394.0)),
 'Peckham Rye': (('2',),(1246.3, 265.2)),
 'Penge West': (('4',), (1377.0, 114.0)),
 'Perivale': (('4',), (256.5, 872.0)),
 'Piccadilly Circus': (('1',), (978.5, 637.0)),
 'Pimlico': (('1',), (884.0, 434.0)),
 'Pinner': (('5',), (367.5, 1166.0)),
 'Plaistow': (('3',), (1758.5, 788.0)),
 'Pontoon Dock': (('3',), (1847.0, 541.0)),
 'Poplar': (('2',), (1588.5, 627.0)),
 'Preston Road': (('4',), (597.0, 1107.0)),
 'Prince Regent': (('3',), (1848.5, 591.0)),
 'Pudding Mill Lane': (('2', '3'), (1658.5, 847.0)),
 'Putney Bridge': (('2',), (660.5, 367.0)),
 "Queen's Park": (('2',), (564.5, 918.0)),
 'Queensbury': (('4',), (648.5, 1146.0)),
 'Queens Road Peckham': (('2',), (1273.6, 288.8)),
 'Queensway': (('1',), (752.5, 705.0)),
 'Ravenscourt Park': (('2',), (529.0, 535.0)),
 'Rayners Lane': (('5',), (310.0, 1118.0)),
 'Redbridge': (('4',), (1778.0, 1050.0)),
 "Regent's Park": (('1',), (904.5, 770.0)),
 'Richmond': (('4',), (387.0, 382.0)),
 'Rickmansworth': (('7',), (265.5, 1267.0)),
 'Roding Valley': (('5',), (1744.0, 1200.0)),
 'Rotherhithe': (('2',), (1461.0, 546.0)),
 'Royal Albert': (('3',), (1874.0, 563.0)),
 'Royal Oak': (('2',), (622.0, 819.0)),
 'Royal Victoria': (('3',), (1795.0, 630.0)),
 'Ruislip': (('6',), (228.5, 1186.0)),
 'Ruislip Gardens': (('5',), (197.5, 1109.0)),
 'Ruislip Manor': (('6',), (264.0, 1174.0)),
 'Russell Square': (('1',), (1095.5, 761.0)),
 'Schreditch High Street': (('1',), (1462.5, 764.0)),
 'Seven Sisters': (('3',), (1446.5, 1081.0)),
 'Shadwell': (('2',), (1462.5, 641.0)),
 "Sheperd's Bush": (('2',), (560.0, 629.0)),
 "Shepherd's Bush": (('2',), (613.0, 706.0)),
 'Sloane Square': (('1',), (829.0, 540.0)),
 'Snaresbrook': (('4',), (1712.5, 1101.0)),
 'South Acton': (('3',), (437.0, 604.0)),
 'South Ealing': (('3',), (295.0, 542.0)),
 'South Hampstead': (('2',), (755.0, 896.0)),
 'South Harrow': (('5',), (317.0, 1067.0)),
 'South Kensington': (('1',), (768.5, 537.0)),
 'South Kenton': (('4',), (561.5, 1088.0)),
 'South Quay': (('2',), (1588.5, 475.0)),
 'South Ruislip': (('5',), (197.5, 1055.0)),
 'South Tottenham': (('3',), (1505.5, 1118.0)),
 'South Wimbeldon': (('3', '4'), (793.5, 55.0)),
 'South Woodford': (('4',), (1712.5, 1128.0)),
 'Southfields': (('3',), (662.0, 301.0)),
 'Southgate': (('4',), (1377.0, 1258.0)),
 'Southwark': (('1',), (1097.0, 452.0)),
 "St. James's Park": (('1',), (921.0, 543.0)),
 "St. John's Wood": (('2',), (838.0, 903.0)),
 "St. Paul's": (('1',), (1175.5, 690.0)),
 'Stamford Brook': (('2',), (469.5, 535.0)),
 'Stanmore': (('5',), (645.5, 1203.0)),
 'Stepney Green': (('2',), (1492.0, 720.0)),
 'Stockwell': (('2',), (990.5, 253.0)),
 'Stonebridge Park': (('3',), (561.5, 1018.0)),
 'Stratford': (('3',), (1668.5, 879.0)),
 'Sudbury Hill': (('4',), (317.0, 1023.0)),
 'Sudbury Town': (('4',), (317.0, 977.0)),
 'Surrey Quays': (('2',), (1459.5, 458.0)),
 'Swiss Cottage': (('2',), (820.5, 921.0)),
 'Sydenham': (('3',), (1375.5, 148.0)),
 'Temple': (('1',), (1100.0, 543.0)),
 'Theydon Bois': (('6',), (1709.5, 1334.0)),
 'Tooting Bec': (('3',), (869.0, 131.0)),
 'Tooting Broadway': (('3',), (842.5, 107.0)),
 'Tottenham Court Road': (('1',), (1032.0, 705.0)),
 'Tottenham Hale': (('3',), (1492.0, 1081.0)),
 'Totteridge & Whetstone': (('4',), (1137.0, 1291.0)),
 'Tower Gateway': (('1',), (1383.5, 602.0)),
 'Tower Hill': (('1',), (1360.5, 623.0)),
 'Tufnell Park': (('2',), (1134.0, 1075.0)),
 'Turnham Green': (('2', '3'), (419.5, 533.0)),
 'Turnpike Lane': (('3',), (1375.5, 1149.0)),
 'Upminster': (('6',), (2020.5, 1052.0)),
 'Upminster Bridge': (('6',), (1994.0, 1027.0)),
 'Upney': (('4',), (1847.5, 884.0)),
 'Upper Holloway': (('2',), (1229.0, 1075.0)),
 'Upton Park': (('3',), (1779.5, 814.0)),
 'Uxbridge': (('6',), (34.5, 1180.0)),
 'Vauxhall': (('1', '2'), (906.0, 335.0)),
 'Victoria': (('1',), (884.0, 539.0)),
 'Walthamstow Central': (('3',), (1616.5, 1082.0)),
 "Walthamstow Queen's Road": (('3',), (1557.5, 1026.0)),
 'Wanstead': (('4',), (1745.0, 1047.0)),
 'Wanstead Park': (('3',), (1807.5, 930.0)),
 'Wandsworth Road': (('2',), (864.9, 293.293)),
 'Wapping': (('2',), (1464.0, 585.0)),
 'Warren Street': (('1',), (1030.5, 804.0)),
 'Warwick Avenue': (('2',), (603.0, 857.0)),
 'Waterloo': (('1',), (1049.5, 481.0)),
 'Watford': (('7',), (276.0, 1311.0)),
 'Watford High Street': (('8',), (567.5, 1323.0)),
 'Watford Junction': (('1000',), (567.5, 1351.0)),
 'Wembley Central': (('4',), (563.0, 1041.0)),
 'Wembley Park': (('4',), (657.5, 1078.0)),
 'West Acton': (('3',), (382.5, 705.0)),
 'West Brompton': (('2',), (662.0, 478.0)),
 'West Croydon': (('5',), (1375.5, 33.0)),
 'West Finchley': (('4',), (1134.0, 1236.0)),
 'West Ham': (('3',), (1708.0, 765.0)),
 'West Hampstead': (('2',), (774.5, 962.0)),
 'West Harrow': (('5',), (391.0, 1104.0)),
 'West India Quay': (('2',), (1588.5, 584.0)),
 'West Kensington': (('2',), (638.5, 536.0)),
 'West Ruislip': (('6',), (197.5, 1220.0)),
 'West Silvertown': (('3',), (1801.0, 585.0)),
 'Westbourne Park': (('2',), (603.0, 795.0)),
 'Westferry': (('2',), (1554.0, 627.0)),
 'Westminster': (('1',), (984.5, 540.0)),
 'White City': (('2',), (539.0, 706.0)),
 'Whitechapel': (('2',), (1464.0, 696.0)),
 'Willesden Green': (('2', '3'), (725.5, 1015.0)),
 'Willesden Junction': (('3',), (564.5, 962.0)),
 'Wimbeldon': (('3',), (662.0, 244.0)),
 'Wimbeldon Park': (('3',), (660.5, 273.0)),
 'Wood Green': (('3',), (1375.5, 1175.0)),
 'Woodford': (('4',), (1709.5, 1156.0)),
 'Woodrange Park': (('3', '4'), (1820.5, 894.0)),
 'Woodside Park': (('4',), (1134.0, 1266.0)),
 'Woolwich Arsenal': (('4',), (2028.0, 363.0))}


edges = \
[('Acton Central', 'South Acton', ('Overground',)),
 ('Acton Central', 'Willesden Junction', ('Overground',)),
 ('Acton Town', 'Chiswick Park', ('District',)),
 ('Acton Town', 'Ealing Common', ('District', 'Piccadilly')),
 ('Acton Town', 'South Ealing', ('Piccadilly',)),
 ('Acton Town', 'Turnham Green', ('Piccadilly',)),
 ('Aldgate', 'Liverpool Street', ('Circle', 'Metropolitan')),
 ('Aldgate', 'Tower Hill', ('Circle',)),
 ('Aldgate East', 'Liverpool Street', ('Hammersmith & City',)),
 ('Aldgate East', 'Tower Hill', ('District',)),
 ('Aldgate East', 'Whitechapel', ('District', 'Hammersmith & City')),
 ('All Saints', 'Langdon Park', ('Docklands Light Rail',)),
 ('All Saints', 'Poplar', ('Docklands Light Rail',)),
 ('Alperton', 'Park Royal', ('Piccadilly',)),
 ('Alperton', 'Sudbury Town', ('Piccadilly',)),
 ('Amersham', 'Chaifont & Latimer', ('Metropolitan',)),
 ('Anerley', 'Norwood Junction', ('Overground',)),
 ('Anerley', 'Penge West', ('Overground',)),
 ('Angel', "King's Cross St. Pancras", ('Northern',)),
 ('Angel', 'Old Street', ('Northern',)),
 ('Archway', 'Highgate', ('Northern',)),
 ('Archway', 'Tufnell Park', ('Northern',)),
 ('Arnos Grove', 'Bounds Green', ('Piccadilly',)),
 ('Arnos Grove', 'Southgate', ('Piccadilly',)),
 ('Arsenal', 'Finsbury Park', ('Piccadilly',)),
 ('Arsenal', 'Holloway Road', ('Piccadilly',)),
 ('Baker Street', 'Bond Street', ('Jubilee',)),
 ('Baker Street', 'Edgware Road', ('Circle', 'Hammersmith & City')),
 ('Baker Street', 'Finchley Road', ('Metropolitan',)),
 ('Baker Street', 'Great Portland Street', ('Circle', 'Hammersmith & City', 'Metropolitan')),
 ('Baker Street', 'Marylebone', ('Bakerloo',)),
 ('Baker Street', "Regent's Park", ('Bakerloo',)),
 ('Baker Street', "St. John's Wood", ('Jubilee',)),
 ('Balham', 'Clapham South', ('Northern',)),
 ('Balham', 'Tooting Bec', ('Northern',)),
 ('Bank', 'Liverpool Street', ('Central',)),
 ('Bank', 'London Bridge', ('Northern',)),
 ('Bank', 'Moorgate', ('Northern',)),
 ('Bank', 'Shadwell', ('Docklands Light Rail',)),
 ('Bank', "St. Paul's", ('Central',)),
 ('Bank', 'Waterloo', ('Waterloo & City',)),
 ('Barbican', 'Farringdon', ('Circle', 'Hammersmith & City', 'Metropolitan')),
 ('Barbican', 'Moorgate', ('Circle', 'Hammersmith & City', 'Metropolitan')),
 ('Barking', 'East Ham', ('District', 'Hammersmith & City')),
 ('Barking', 'Upney', ('District',)),
 ('Barking', 'Woodrange Park', ('Overground',)),
 ('Barkingside', 'Fairlop', ('Central',)),
 ('Barkingside', 'Newbury Park', ('Central',)),
 ('Barons Court', "Earl's Court", ('Piccadilly',)),
 ('Barons Court', 'Hammersmith', ('District', 'Piccadilly')),
 ('Barons Court', 'West Kensington', ('District',)),
 ('Bayswater', 'Notting Hill Gate', ('Circle', 'District')),
 ('Bayswater', 'Paddington', ('Circle', 'District')),
 ('Beckton', 'Gallions Reach', ('Docklands Light Rail',)),
 ('Beckton Park', 'Cyprus', ('Docklands Light Rail',)),
 ('Beckton Park', 'Royal Albert', ('Docklands Light Rail',)),
 ('Becontree', 'Dagenham Heathway', ('District',)),
 ('Becontree', 'Upney', ('District',)),
 ('Belsize Park', 'Chalk Farm', ('Northern',)),
 ('Belsize Park', 'Hampstead', ('Northern',)),
 ('Bermondsey', 'Canada Water', ('Jubilee',)),
 ('Bermondsey', 'London Bridge', ('Jubilee',)),
 ('Bethnal Green', 'Liverpool Street', ('Central',)),
 ('Bethnal Green', 'Mile End', ('Central',)),
 ('Blackfriars', 'Mansion House', ('Circle', 'District')),
 ('Blackfriars', 'Temple', ('Circle', 'District')),
 ('Blackhorse Road', 'South Tottenham', ('Overground',)),
 ('Blackhorse Road', 'Tottenham Hale', ('Victoria',)),
 ('Blackhorse Road', 'Walthamstow Central', ('Victoria',)),
 ('Blackhorse Road', "Walthamstow Queen's Road", ('Overground',)),
 ('Blackwall', 'East India', ('Docklands Light Rail',)),
 ('Blackwall', 'Poplar', ('Docklands Light Rail',)),
 ('Bond Street', 'Green Park', ('Jubilee',)),
 ('Bond Street', 'Marble Arch', ('Central',)),
 ('Bond Street', 'Oxford Circus', ('Central',)),
 ('Borough', 'Elephant & Castle', ('Northern',)),
 ('Borough', 'London Bridge', ('Northern',)),
 ('Boston Manor', 'Northfields', ('Piccadilly',)),
 ('Boston Manor', 'Osterley', ('Piccadilly',)),
 ('Bounds Green', 'Wood Green', ('Piccadilly',)),
 ('Bow Church', 'Devons Road', ('Docklands Light Rail',)),
 ('Bow Church', 'Pudding Mill Lane', ('Docklands Light Rail',)),
 ('Bow Road', 'Bromley-by-Bow', ('District', 'Hammersmith & City')),
 ('Bow Road', 'Mile End', ('District', 'Hammersmith & City')),
 ('Brent Cross', 'Golders Green', ('Northern',)),
 ('Brent Cross', 'Hendon Central', ('Northern',)),
 ('Brixton', 'Stockwell', ('Victoria',)),
 ('Brockley', 'Honor Oak Park', ('Overground',)),
 ('Brockley', 'New Cross Gate', ('Overground',)),
 ('Bromley-by-Bow', 'West Ham', ('District', 'Hammersmith & City')),
 ('Brondesbury', 'Brondesbury Park', ('Overground',)),
 ('Brondesbury', 'West Hampstead', ('Overground',)),
 ('Brondesbury Park', 'Kensal Rise', ('Overground',)),
 ('Buckhurst Hill', 'Loughton', ('Central',)),
 ('Buckhurst Hill', 'South Woodford', ('Central',)),
 ('Burnt Oak', 'Colindale', ('Northern',)),
 ('Burnt Oak', 'Edgware', ('Northern',)),
 ('Bushey', 'Carpenders Park', ('Overground',)),
 ('Bushey', 'Watford High Street', ('Overground',)),
 ('Caledonian Road', 'Holloway Road', ('Piccadilly',)),
 ('Caledonian Road', "King's Cross St. Pancras", ('Piccadilly',)),
 ('Caledonian Road & Barnsbury', 'Camden Road', ('Overground',)),
 ('Caledonian Road & Barnsbury', 'Highbury & Islington', ('Overground',)),
 ('Camden Road', 'Kentish Town West', ('Overground',)),
 ('Camden Town', 'Chalk Farm', ('Northern',)),
 ('Camden Town', 'Euston', ('Northern',)),
 ('Camden Town', 'Kentish Town', ('Northern',)),
 ('Camden Town', 'Mornington Crescent', ('Northern',)),
 ('Canada Water', 'Canary Wharf', ('Jubilee',)),
 ('Canada Water', 'Rotherhithe', ('Overground',)),
 ('Canada Water', 'Surrey Quays', ('Overground',)),
 ('Canary Wharf', 'Heron Quays', ('Docklands Light Rail',)),
 ('Canary Wharf', 'North Greenwich', ('Jubilee',)),
 ('Canary Wharf', 'West India Quay', ('Docklands Light Rail',)),
 ('Canning Town', 'East India', ('Docklands Light Rail',)),
 ('Canning Town', 'North Greenwich', ('Jubilee',)),
 ('Canning Town', 'Royal Victoria', ('Docklands Light Rail',)),
 ('Canning Town', 'West Ham', ('Jubilee',)),
 ('Canning Town', 'West Silvertown', ('Docklands Light Rail',)),
 ('Cannon Street', 'Mansion House', ('Circle', 'District')),
 ('Cannon Street', 'Monument', ('Circle', 'District')),
 ('Canonbury', 'Dalston Kingsland', ('Overground',)),
 ('Canonbury', 'Highbury & Islington', ('Overground',)),
 ('Canons Park', 'Queensbury', ('Jubilee',)),
 ('Canons Park', 'Stanmore', ('Jubilee',)),
 ('Carpenders Park', 'Hatch End', ('Overground',)),
 ('Chaifont & Latimer', 'Chesham', ('Metropolitan',)),
 ('Chaifont & Latimer', 'Chorleywood', ('Metropolitan',)),
 ('Chancery Lane', 'Holborn', ('Central',)),
 ('Chancery Lane', "St. Paul's", ('Central',)),
 ('Charing Cross', 'Embankment', ('Bakerloo', 'Northern')),
 ('Charing Cross', 'Leicester Square', ('Northern',)),
 ('Charing Cross', 'Piccadilly Circus', ('Bakerloo',)),
 ('Chigwell', 'Grange Hill', ('Central',)),
 ('Chigwell', 'Roding Valley', ('Central',)),
 ('Chiswick Park', 'Turnham Green', ('District',)),
 ('Chorleywood', 'Rickmansworth', ('Metropolitan',)),
 ('Clapham Common', 'Clapham North', ('Northern',)),
 ('Clapham Common', 'Clapham South', ('Northern',)),
 ('Clapham Junction', 'Imperial Wharf', ('Overground',)),
 ('Clapham North', 'Stockwell', ('Northern',)),
 ('Cockfosters', 'Oakwood', ('Piccadilly',)),
 ('Colindale', 'Hendon Central', ('Northern',)),
 ('Colliers Wood', 'South Wimbeldon', ('Northern',)),
 ('Colliers Wood', 'Tooting Broadway', ('Northern',)),
 ('Covent Garden', 'Holborn', ('Piccadilly',)),
 ('Covent Garden', 'Leicester Square', ('Piccadilly',)),
 ('Crossharbour', 'Mudchute', ('Docklands Light Rail',)),
 ('Crossharbour', 'South Quay', ('Docklands Light Rail',)),
 ('Crouch Hill', 'Harringay Green Lanes', ('Overground',)),
 ('Crouch Hill', 'Upper Holloway', ('Overground',)),
 ('Croxley', 'Moor Park', ('Metropolitan',)),
 ('Croxley', 'Watford', ('Metropolitan',)),
 ('Crystal Palace', 'Sydenham', ('Overground',)),
 ('Custom House for ExCeL', 'Prince Regent', ('Docklands Light Rail',)),
 ('Custom House for ExCeL', 'Royal Victoria', ('Docklands Light Rail',)),
 ('Cutty Sark for Maritime Greenwich', 'Greenwich', ('Docklands Light Rail',)),
 ('Cutty Sark for Maritime Greenwich',
  'Island Gardens',
  ('Docklands Light Rail',)),
 ('Cyprus', 'Gallions Reach', ('Docklands Light Rail',)),
 ('Dagenham East', 'Dagenham Heathway', ('District',)),
 ('Dagenham East', 'Elm Park', ('District',)),
 ('Dalston Junction', 'Dalston Kingsland', ('Overground',)),
 ('Dalston Junction', 'Haggerston', ('Overground',)),
 ('Dalston Kingsland', 'Hackney Central', ('Overground',)),
 ('Debden', 'Loughton', ('Central',)),
 ('Debden', 'Theydon Bois', ('Central',)),
 ('Deptford Bridge', 'Elverson Road', ('Docklands Light Rail',)),
 ('Deptford Bridge', 'Greenwich', ('Docklands Light Rail',)),
 ('Devons Road', 'Langdon Park', ('Docklands Light Rail',)),
 ('Dollis Hill', 'Neasden', ('Jubilee',)),
 ('Dollis Hill', 'Willesden Green', ('Jubilee',)),
 ('Ealing Broadway', 'Ealing Common', ('District',)),
 ('Ealing Broadway', 'West Acton', ('Central',)),
 ('Ealing Common', 'North Ealing', ('Piccadilly',)),
 ("Earl's Court", 'Gloucester Road', ('District', 'Piccadilly')),
 ("Earl's Court", 'High Street Kensington', ('District',)),
 ("Earl's Court", 'Kensington (Olympia)', ('District',)),
 ("Earl's Court", 'West Brompton', ('District',)),
 ("Earl's Court", 'West Kensington', ('District',)),
 ('East Acton', 'North Acton', ('Central',)),
 ('East Acton', 'White City', ('Central',)),
 ('Eastcote', 'Rayners Lane', ('Metropolitan', 'Piccadilly')),
 ('Eastcote', 'Ruislip Manor', ('Metropolitan', 'Piccadilly')),
 ('East Finchley', 'Finchley Central', ('Northern',)),
 ('East Finchley', 'Highgate', ('Northern',)),
 ('East Ham', 'Upton Park', ('District', 'Hammersmith & City')),
 ('East Putney', 'Putney Bridge', ('District',)),
 ('East Putney', 'Southfields', ('District',)),
 ('Edgware Road', 'Marylebone', ('Bakerloo',)),
 ('Edgware Road',  'Paddington',  ('Bakerloo', 'Circle', 'District', 'Hammersmith & City')),
 ('Elephant & Castle', 'Kennington', ('Northern',)),
 ('Elephant & Castle', 'Lambeth North', ('Bakerloo',)),
 ('Elm Park', 'Hornchurch', ('District',)),
 ('Elverson Road', 'Lewisham', ('Docklands Light Rail',)),
 ('Embankment', 'Temple', ('Circle', 'District')),
 ('Embankment', 'Waterloo', ('Bakerloo', 'Northern')),
 ('Embankment', 'Westminster', ('Circle', 'District')),
 ('Epping', 'Theydon Bois', ('Central',)),
 ('Euston', "King's Cross St. Pancras", ('Northern', 'Victoria')),
 ('Euston', 'Mornington Crescent', ('Northern',)),
 ('Euston', 'South Hampstead', ('Overground',)),
 ('Euston', 'Warren Street', ('Northern', 'Victoria')),
 ('Euston Square',  'Great Portland Street',  ('Circle', 'Hammersmith & City', 'Metropolitan')),
 ('Euston Square',  "King's Cross St. Pancras",  ('Circle', 'Hammersmith & City', 'Metropolitan')),
 ('Fairlop', 'Hainault', ('Central',)),
 ('Farringdon',  "King's Cross St. Pancras",  ('Circle', 'Hammersmith & City', 'Metropolitan')),
 ('Finchley Central', 'Mill Hill East', ('Northern',)),
 ('Finchley Central', 'West Finchley', ('Northern',)),
 ('Finchley Road', 'Swiss Cottage', ('Jubilee',)),
 ('Finchley Road', 'Wembley Park', ('Metropolitan',)),
 ('Finchley Road', 'West Hampstead', ('Jubilee',)),
 ('Finchley Road & Frognal', 'Hamstead Heath', ('Overground',)),
 ('Finchley Road & Frognal', 'West Hampstead', ('Overground',)),
 ('Finsbury Park', 'Highbury & Islington', ('Victoria',)),
 ('Finsbury Park', 'Manor House', ('Piccadilly',)),
 ('Finsbury Park', 'Seven Sisters', ('Victoria',)),
 ('Forest Hill', 'Honor Oak Park', ('Overground',)),
 ('Forest Hill', 'Sydenham', ('Overground',)),
 ('Fulham Broadway', 'Parsons Green', ('District',)),
 ('Fulham Broadway', 'West Brompton', ('District',)),
 ('Gants Hill', 'Newbury Park', ('Central',)),
 ('Gants Hill', 'Redbridge', ('Central',)),
 ('Gloucester Road', 'High Street Kensington', ('Circle',)),
 ('Gloucester Road', 'South Kensington', ('Circle', 'District', 'Piccadilly')),
 ('Golders Green', 'Hampstead', ('Northern',)),
 ('Goldhawk Road', 'Hammersmith', ('Hammersmith & City',)),
 ('Goldhawk Road', "Sheperd's Bush", ('Hammersmith & City',)),
 ('Goodge Street', 'Tottenham Court Road', ('Northern',)),
 ('Goodge Street', 'Warren Street', ('Northern',)),
 ('Gospel Oak', 'Hamstead Heath', ('Overground',)),
 ('Gospel Oak', 'Kentish Town West', ('Overground',)),
 ('Gospel Oak', 'Upper Holloway', ('Overground',)),
 ('Grange Hill', 'Hainault', ('Central',)),
 ('Greenford', 'Northolt', ('Central',)),
 ('Greenford', 'Perivale', ('Central',)),
 ('Green Park', 'Hyde Park Corner', ('Piccadilly',)),
 ('Green Park', 'Oxford Circus', ('Victoria',)),
 ('Green Park', 'Piccadilly Circus', ('Piccadilly',)),
 ('Green Park', 'Victoria', ('Victoria',)),
 ('Green Park', 'Westminster', ('Jubilee',)),
 ('Gunnesbury', 'Kew Gardens', ('District', 'Overground')),
 ('Gunnesbury', 'South Acton', ('Overground',)),
 ('Gunnesbury', 'Turnham Green', ('District',)),
 ('Hackney Central', 'Homerton', ('Overground',)),
 ('Hackney Wick', 'Homerton', ('Overground',)),
 ('Hackney Wick', 'Stratford', ('Overground',)),
 ('Haggerston', 'Hoxton', ('Overground',)),
 ('Hammersmith', 'Ravenscourt Park', ('District',)),
 ('Hammersmith', 'Turnham Green', ('Piccadilly',)),
 ('Hanger Lane', 'North Acton', ('Central',)),
 ('Hanger Lane', 'Perivale', ('Central',)),
 ('Harlesden', 'Stonebridge Park', ('Bakerloo', 'Overground')),
 ('Harlesden', 'Willesden Junction', ('Bakerloo', 'Overground')),
 ('Harringay Green Lanes', 'South Tottenham', ('Overground',)),
 ('Harrow-on-the-Hill', 'North Harrow', ('Metropolitan',)),
 ('Harrow-on-the-Hill', 'Northwick Park', ('Metropolitan',)),
 ('Harrow-on-the-Hill', 'West Harrow', ('Metropolitan',)),
 ('Harrow & Wealdstone', 'Headstone Lane', ('Overground',)),
 ('Harrow & Wealdstone', 'Kenton', ('Bakerloo', 'Overground')),
 ('Hatch End', 'Headstone Lane', ('Overground',)),
 ('Hatton Cross', 'Heathrow Terminals 1,2,3', ('Piccadilly',)),
 ('Hatton Cross', 'Hounslow West', ('Piccadilly',)),
 ('Heron Quays', 'South Quay', ('Docklands Light Rail',)),
 ('High Barnet', 'Totteridge & Whetstone', ('Northern',)),
 ('Highbury & Islington', "King's Cross St. Pancras", ('Victoria',)),
 ('High Street Kensington', 'Notting Hill Gate', ('Circle', 'District')),
 ('Hillingdon', 'Ickenham', ('Metropolitan', 'Piccadilly')),
 ('Hillingdon', 'Uxbridge', ('Metropolitan', 'Piccadilly')),
 ('Holborn', 'Russell Square', ('Piccadilly',)),
 ('Holborn', 'Tottenham Court Road', ('Central',)),
 ('Holland Park', 'Notting Hill Gate', ('Central',)),
 ('Holland Park', "Shepherd's Bush", ('Central',)),
 ('Hornchurch', 'Upminster Bridge', ('District',)),
 ('Hounslow Central', 'Hounslow East', ('Piccadilly',)),
 ('Hounslow Central', 'Hounslow West', ('Piccadilly',)),
 ('Hounslow East', 'Osterley', ('Piccadilly',)),
 ('Hoxton', 'Schreditch High Street', ('Overground',)),
 ('Hyde Park Corner', 'Knightsbridge', ('Piccadilly',)),
 ('Ickenham', 'Ruislip', ('Metropolitan', 'Piccadilly')),
 ('Imperial Wharf', 'West Brompton', ('Overground',)),
 ('Island Gardens', 'Mudchute', ('Docklands Light Rail',)),
 ('Kennington', 'Oval', ('Northern',)),
 ('Kennington', 'Waterloo', ('Northern',)),
 ('Kensal Green', "Queen's Park", ('Bakerloo', 'Overground')),
 ('Kensal Green', 'Willesden Junction', ('Bakerloo', 'Overground')),
 ('Kensal Rise', 'Willesden Junction', ('Overground',)),
 ('Kensington (Olympia)', "Shepherd's Bush", ('Overground',)),
 ('Kensington (Olympia)', 'West Brompton', ('Overground',)),
 ('Kentish Town', 'Tufnell Park', ('Northern',)),
 ('Kenton', 'South Kenton', ('Bakerloo', 'Overground')),
 ('Kew Gardens', 'Richmond', ('District', 'Overground')),
 ('Kilburn', 'West Hampstead', ('Jubilee',)),
 ('Kilburn', 'Willesden Green', ('Jubilee',)),
 ('Kilburn High Road', "Queen's Park", ('Overground',)),
 ('Kilburn High Road', 'South Hampstead', ('Overground',)),
 ('Kilburn Park', 'Maida Vale', ('Bakerloo',)),
 ('Kilburn Park', "Queen's Park", ('Bakerloo',)),
 ('King George V', 'London City Airport', ('Docklands Light Rail',)),
 ('King George V', 'Woolwich Arsenal', ('Docklands Light Rail',)),
 ('Kingsbury', 'Queensbury', ('Jubilee',)),
 ('Kingsbury', 'Wembley Park', ('Jubilee',)),
 ("King's Cross St. Pancras", 'Russell Square', ('Piccadilly',)),
 ('Knightsbridge', 'South Kensington', ('Piccadilly',)),
 ('Ladbroke Grove', 'Latimer Road', ('Hammersmith & City',)),
 ('Ladbroke Grove', 'Westbourne Park', ('Hammersmith & City',)),
 ('Lambeth North', 'Waterloo', ('Bakerloo',)),
 ('Lancaster Gate', 'Marble Arch', ('Central',)),
 ('Lancaster Gate', 'Queensway', ('Central',)),
 ('Latimer Road', "Sheperd's Bush", ('Hammersmith & City',)),
 ('Leicester Square', 'Piccadilly Circus', ('Piccadilly',)),
 ('Leicester Square', 'Tottenham Court Road', ('Northern',)),
 ('Leyton', 'Leytonstone', ('Central',)),
 ('Leyton', 'Stratford', ('Central',)),
 ('Leyton Midland Road', 'Leytonstone High Road', ('Overground',)),
 ('Leyton Midland Road', "Walthamstow Queen's Road", ('Overground',)),
 ('Leytonstone', 'Snaresbrook', ('Central',)),
 ('Leytonstone', 'Wanstead', ('Central',)),
 ('Leytonstone High Road', 'Wanstead Park', ('Overground',)),
 ('Limehouse', 'Shadwell', ('Docklands Light Rail',)),
 ('Limehouse', 'Westferry', ('Docklands Light Rail',)),
 ('Liverpool Street',  'Moorgate',  ('Circle', 'Hammersmith & City', 'Metropolitan')),
 ('London Bridge', 'Southwark', ('Jubilee',)),
 ('London City Airport', 'Pontoon Dock', ('Docklands Light Rail',)),
 ('Maida Vale', 'Warwick Avenue', ('Bakerloo',)),
 ('Manor House', 'Turnpike Lane', ('Piccadilly',)),
 ('Mile End', 'Stepney Green', ('District', 'Hammersmith & City')),
 ('Mile End', 'Stratford', ('Central',)),
 ('Monument', 'Tower Hill', ('Circle', 'District')),
 ('Moorgate', 'Old Street', ('Northern',)),
 ('Moor Park', 'Northwood', ('Metropolitan',)),
 ('Moor Park', 'Rickmansworth', ('Metropolitan',)),
 ('Morden', 'South Wimbeldon', ('Northern',)),
 ('Neasden', 'Wembley Park', ('Jubilee',)),
 ('New Cross', 'Surrey Quays', ('Overground',)),
 ('New Cross Gate', 'Surrey Quays', ('Overground',)),
 ('North Acton', 'West Acton', ('Central',)),
 ('North Ealing', 'Park Royal', ('Piccadilly',)),
 ('Northfields', 'South Ealing', ('Piccadilly',)),
 ('North Harrow', 'Pinner', ('Metropolitan',)),
 ('Northolt', 'South Ruislip', ('Central',)),
 ('North Wembley', 'South Kenton', ('Bakerloo', 'Overground')),
 ('North Wembley', 'Wembley Central', ('Bakerloo', 'Overground')),
 ('Northwick Park', 'Preston Road', ('Metropolitan',)),
 ('Northwood', 'Northwood Hills', ('Metropolitan',)),
 ('Northwood Hills', 'Pinner', ('Metropolitan',)),
 ('Norwood Junction', 'West Croydon', ('Overground',)),
 ('Notting Hill Gate', 'Queensway', ('Central',)),
 ('Oakwood', 'Southgate', ('Piccadilly',)),
 ('Oval', 'Stockwell', ('Northern',)),
 ('Oxford Circus', 'Piccadilly Circus', ('Bakerloo',)),
 ('Oxford Circus', "Regent's Park", ('Bakerloo',)),
 ('Oxford Circus', 'Tottenham Court Road', ('Central',)),
 ('Oxford Circus', 'Warren Street', ('Victoria',)),
 ('Paddington', 'Royal Oak', ('Hammersmith & City',)),
 ('Paddington', 'Warwick Avenue', ('Bakerloo',)),
 ('Parsons Green', 'Putney Bridge', ('District',)),
 ('Penge West', 'Sydenham', ('Overground',)),
 ('Pimlico', 'Vauxhall', ('Victoria',)),
 ('Pimlico', 'Victoria', ('Victoria',)),
 ('Plaistow', 'Upton Park', ('District', 'Hammersmith & City')),
 ('Plaistow', 'West Ham', ('District', 'Hammersmith & City')),
 ('Pontoon Dock', 'West Silvertown', ('Docklands Light Rail',)),
 ('Poplar', 'Westferry', ('Docklands Light Rail',)),
 ('Poplar', 'West India Quay', ('Docklands Light Rail',)),
 ('Preston Road', 'Wembley Park', ('Metropolitan',)),
 ('Prince Regent', 'Royal Albert', ('Docklands Light Rail',)),
 ('Pudding Mill Lane', 'Stratford', ('Docklands Light Rail',)),
 ('Ravenscourt Park', 'Stamford Brook', ('District',)),
 ('Rayners Lane', 'South Harrow', ('Piccadilly',)),
 ('Rayners Lane', 'West Harrow', ('Metropolitan',)),
 ('Redbridge', 'Wanstead', ('Central',)),
 ('Roding Valley', 'Woodford', ('Central',)),
 ('Rotherhithe', 'Wapping', ('Overground',)),
 ('Royal Oak', 'Westbourne Park', ('Hammersmith & City',)),
 ('Ruislip', 'Ruislip Manor', ('Metropolitan', 'Piccadilly')),
 ('Ruislip Gardens', 'South Ruislip', ('Central',)),
 ('Ruislip Gardens', 'West Ruislip', ('Central',)),
 ('Schreditch High Street', 'Whitechapel', ('Overground',)),
 ('Seven Sisters', 'Tottenham Hale', ('Victoria',)),
 ('Shadwell', 'Tower Gateway', ('Docklands Light Rail',)),
 ('Shadwell', 'Wapping', ('Overground',)),
 ('Shadwell', 'Whitechapel', ('Overground',)),
 ("Shepherd's Bush", 'White City', ('Central',)),
 ("Shepherd's Bush", 'Willesden Junction', ('Overground',)),
 ('Sloane Square', 'South Kensington', ('Circle', 'District')),
 ('Sloane Square', 'Victoria', ('Circle', 'District')),
 ('Snaresbrook', 'South Woodford', ('Central',)),
 ('Southfields', 'Wimbeldon Park', ('District',)),
 ('South Harrow', 'Sudbury Hill', ('Piccadilly',)),
 ('Southwark', 'Waterloo', ('Jubilee',)),
 ('Stamford Brook', 'Turnham Green', ('District',)),
 ('Stepney Green', 'Whitechapel', ('District', 'Hammersmith & City')),
 ("St. James's Park", 'Victoria', ('Circle', 'District')),
 ("St. James's Park", 'Westminster', ('Circle', 'District')),
 ("St. John's Wood", 'Swiss Cottage', ('Jubilee',)),
 ('Stockwell', 'Vauxhall', ('Victoria',)),
 ('Stonebridge Park', 'Wembley Central', ('Bakerloo', 'Overground')),
 ('Stratford', 'West Ham', ('Jubilee',)),
 ('Sudbury Hill', 'Sudbury Town', ('Piccadilly',)),
 ('Tooting Bec', 'Tooting Broadway', ('Northern',)),
 ('Totteridge & Whetstone', 'Woodside Park', ('Northern',)),
 ('Turnpike Lane', 'Wood Green', ('Piccadilly',)),
 ('Upminster', 'Upminster Bridge', ('District',)),
 ('Wanstead Park', 'Woodrange Park', ('Overground',)),
 ('Waterloo', 'Westminster', ('Jubilee',)),
 ('Watford High Street', 'Watford Junction', ('Overground',)),
 ('Westferry', 'West India Quay', ('Docklands Light Rail',)),
 ('West Finchley', 'Woodside Park', ('Northern',)),
 ('Wimbeldon', 'Wimbeldon Park', ('District',)),
 ('Clapham Junction', 'Wandsworth Road', ('Overground',)),
 ('Wandsworth Road', 'Clapham High Street', ('Overground',)),
 ('Clapham High Street', 'Denmark Hill', ('Overground',)),
 ('Denmark Hill','Peckham Rye' , ('Overground',)),
 ('Peckham Rye', 'Queens Road Peckham', ('Overground',)),
 ('Queens Road Peckham', 'Surrey Quays', ('Overground',)),
 ]